[View in Colaboratory](https://colab.research.google.com/github/piyushkhalya/TensorFlow-testing/blob/master/BasicTese2.ipynb)

In [0]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf
from tensorflow import keras

In [5]:
sess = tf.Session()
print(sess.run(total))

7.0


In [6]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
total = a + b
print(a)
print(b)
print(total)

Tensor("Const_2:0", shape=(), dtype=float32)
Tensor("Const_3:0", shape=(), dtype=float32)
Tensor("add_1:0", shape=(), dtype=float32)


In [7]:
print(sess.run({'ab':(a, b), 'total':total}))

{'ab': (3.0, 4.0), 'total': 7.0}


In [8]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1, out2)))

[0.1823057  0.98479116 0.64262474]
[0.73814666 0.79099834 0.82999396]
(array([1.0863347, 1.6745473, 1.0043746], dtype=float32), array([2.0863347, 2.6745472, 2.0043745], dtype=float32))


In [0]:
model = keras.Sequential()
# Adds a densely-connected layer with 64 units to the model:
model.add(keras.layers.Dense(64, activation='relu'))
# Add another:
model.add(keras.layers.Dense(64, activation='relu'))
# Add a softmax layer with 10 output units:
model.add(keras.layers.Dense(10, activation='softmax'))

In [18]:
model
print(model)

In [0]:
model.compile(optimizer=tf.train.AdamOptimizer(0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [22]:
import numpy as np

data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))

model.fit(data, labels, epochs=10, batch_size=32)

Epoch 1/10
1000/1000 [==============================] - 0s 144us/step - loss: 11.4675 - acc: 0.1010
Epoch 2/10
1000/1000 [==============================] - 0s 133us/step - loss: 11.4511 - acc: 0.1190
Epoch 3/10
1000/1000 [==============================] - 0s 130us/step - loss: 11.4436 - acc: 0.1230
Epoch 4/10
1000/1000 [==============================] - 0s 127us/step - loss: 11.4375 - acc: 0.1240
Epoch 5/10
1000/1000 [==============================] - 0s 128us/step - loss: 11.4333 - acc: 0.1360
Epoch 6/10
1000/1000 [==============================] - 0s 135us/step - loss: 11.4285 - acc: 0.1370
Epoch 7/10
1000/1000 [==============================] - 0s 127us/step - loss: 11.4248 - acc: 0.1460
Epoch 8/10
1000/1000 [==============================] - 0s 135us/step - loss: 11.4193 - acc: 0.1520
Epoch 9/10
1000/1000 [==============================] - 0s 134us/step - loss: 11.4147 - acc: 0.1690
Epoch 10/10
1000/1000 [==============================] - 0s 129us/step - loss: 11.4101 - acc: 0.1840

In [24]:
dataset = tf.data.Dataset.from_tensor_slices((data, labels))
dataset = dataset.batch(32).repeat()

val_data = np.random.random((100, 32))
val_labels = np.random.random((100, 10))

val_dataset = tf.data.Dataset.from_tensor_slices((val_data, val_labels))
val_dataset = val_dataset.batch(32).repeat()

model.fit(dataset, epochs=10, steps_per_epoch=30,
          validation_data=val_dataset,
          validation_steps=3)

Epoch 1/10
30/30 [==============================] - 0s 9ms/step - loss: 11.4091 - acc: 0.1719 - val_loss: 11.4749 - val_acc: 0.1667
Epoch 2/10
30/30 [==============================] - 0s 4ms/step - loss: 11.3812 - acc: 0.1865 - val_loss: 11.4352 - val_acc: 0.1146
Epoch 3/10
30/30 [==============================] - 0s 4ms/step - loss: 11.3676 - acc: 0.1823 - val_loss: 11.5657 - val_acc: 0.0938
Epoch 4/10
30/30 [==============================] - 0s 4ms/step - loss: 11.3415 - acc: 0.1781 - val_loss: 11.3330 - val_acc: 0.1146
Epoch 5/10
30/30 [==============================] - 0s 4ms/step - loss: 11.3691 - acc: 0.1917 - val_loss: 11.4811 - val_acc: 0.1771
Epoch 6/10
30/30 [==============================] - 0s 4ms/step - loss: 11.3393 - acc: 0.1917 - val_loss: 11.4300 - val_acc: 0.1146
Epoch 7/10
30/30 [==============================] - 0s 4ms/step - loss: 11.3920 - acc: 0.2000 - val_loss: 11.5693 - val_acc: 0.0938
Epoch 8/10
30/30 [==============================] - 0s 4ms/step - loss: 11.3

In [29]:
model.evaluate([4,6,7,4,2,6,8,8,82,2,0], [1,2,3,4,5,6,7,8,9,0], batch_size=32)

ValueError: ignored

In [27]:
model.evaluate(dataset, steps=30)

30/30 [==============================] - 0s 4ms/step


[11.358759530385335, 0.23125]